Fixing the extraction of hashtags
piscibus/siklid-api pull request #115
Opened 2022-11-16 19:12 UTC by mgamal92

| Q             | A                                                                  |
|---------------|--------------------------------------------------------------------|
| Branch?       | 1.x |
| Bug fix?      | yes  |
| New feature?  | no  |
| Deprecations? | no |
| Tickets       | Fix #109 |
| License       | MIT |

Note: I will create the separate service for that, now I'm working with POC

2022-11-24 13:55 UTC, mgamal92 commented
> @mgamal92 Any progress on this PR?

I'm so sorry, I was so busy the past days. I will give it more time this weekend

2022-12-18 18:42 UTC, imdhemy requested changes
Add unit tests, please.

2022-12-18 18:42 UTC, imdhemy commented on src/Foundation/Util/Hashtag.php
> +            $hashtags[] = u(mb_strtolower($match))->toString();
Could you clarify the idea behind converting the match into a Unicode string?

2022-12-19 04:23 UTC, mgamal92 commented on src/Foundation/Util/Hashtag.php
> +            $hashtags[] = u(mb_strtolower($match))->toString();
It was an extra step so no need for that and removed.

2022-12-19 06:11 UTC, imdhemy requested changes
I added unit tests for different languages and some of them are broken.

https://github.com/piscibus/siklid-api/actions/runs/3728902225/jobs/6324311049#step:10:122

2022-12-31 13:51 UTC, imdhemy approved these changes
Great work! Finally, we have this excellent service! 🎉

2022-12-31 14:50 UTC, imdhemy commented
@mgamal92 
Could you please submit the same PR in the following repo?

https://github.com/piscibus/php-hashtag

2022-12-31 14:53 UTC, mgamal92 commented
Why did you move it to separated repo ?

2022-12-31 14:57 UTC, imdhemy commented
We already planned to publish a package for this service from day 1.

2023-01-07 18:29 UTC, merged