not complete logout only store token
piscibus/siklid-api pull request #144
Opened 2022-11-26 08:00 UTC by Moemen-Gaballah

| Q             | A                                                                  |
|---------------|--------------------------------------------------------------------|
| Branch?       | 1.x                                              |
| Bug fix?      | yes/no                                                             |
| New feature?  | yes/no                   |
| Deprecations? | yes/no  |
| Tickets       | Fix #...            |
| License       | MIT                                                                |

2022-11-26 12:48 UTC, Moemen-Gaballah commented
I have some issue in test(psalm) - and some code legecy.

2022-11-26 17:20 UTC, imdhemy requested changes

2022-11-26 17:20 UTC, imdhemy commented on composer.json
> +    "phpdocumentor/reflection-docblock": "^5.3",
@Moemen-Gaballah Why do we need the following packages?

- phpdocumentor/reflection-docblock
- phpstan/phpdoc-parser

2022-11-26 17:20 UTC, imdhemy commented on config/packages/cache.yaml
> +        default_redis_provider: redis://redis:6379
It would be better to replace the Redis URI with an environment variable.

2022-11-26 17:20 UTC, imdhemy commented on config/packages/cache.yaml
> +            #my.dedicated.cache: null
Add a new line at the end of each file.

2022-11-26 17:20 UTC, imdhemy commented on docker/caddy/Caddyfile
> -        # Publisher JWT key
Revert this change, please.

2022-11-26 17:20 UTC, imdhemy commented on notes
> +docker exec -it siklid_php php bin/console lexik:jwt:generate-keypair
I believe this file was added by mistake.

2022-11-26 17:20 UTC, imdhemy commented on siklid.api.v1.postman_collection.json
> +{
And this as well was added by mistake.

2022-11-26 17:20 UTC, imdhemy commented on src/Controller/Auth/LogoutInterface.php
> +//        dd('logout method');
Remove the commented-out code, please.

2022-11-26 17:20 UTC, imdhemy commented on src/Controller/TokenAuthenticatedInterface.php
> +<?php
Why do we need an empty interface?

2022-11-26 17:22 UTC, imdhemy commented
@Moemen-Gaballah, please, follow this pattern in your comment messages.

https://github.com/piscibus/siklid/discussions/3#discussioncomment-4183666

2022-11-27 09:46 UTC, imdhemy commented
@Moemen-Gaballah 
I forot to thank you about your efforts and time. Don't be worry about my comments, I will guide you till you finish this PR.

Best of luck 🤞

2022-12-02 05:38 UTC, Moemen-Gaballah commented on composer.json
> +    "phpdocumentor/reflection-docblock": "^5.3",
@imdhemy  
حضرتك اللى كنت ضايفهم 
![image](https://user-images.githubusercontent.com/31255104/205222773-b7679d13-255a-49a5-aaa6-ea7f95b11e3e.png)

2022-12-02 05:41 UTC, Moemen-Gaballah commented on config/packages/cache.yaml
> +            #my.dedicated.cache: null
Ok, done but can do any problem ?

2022-12-02 05:47 UTC, Moemen-Gaballah commented on docker/caddy/Caddyfile
> -        # Publisher JWT key
mmmm done 
when do "git checkout HEAD docker/caddy/Caddyfile"
not thing removed
but I removed space.

2022-12-02 05:54 UTC, Moemen-Gaballah commented on notes
> +docker exec -it siklid_php php bin/console lexik:jwt:generate-keypair
sometimes I need run this command (first time is special) maybe as reference for new members.

2022-12-02 05:59 UTC, Moemen-Gaballah commented on src/Controller/TokenAuthenticatedInterface.php
> +<?php
any route I want to be authorized (token still valid) I will implement it

![image](https://user-images.githubusercontent.com/31255104/205225347-a67dc1db-d3de-46ce-8060-b06b5b2520d2.png)

can you help me todo it better ?

2022-12-02 06:14 UTC, Moemen-Gaballah commented on config/packages/cache.yaml
> +        default_redis_provider: redis://redis:6379
Done ISA

2022-12-03 11:32 UTC, imdhemy commented on composer.json
> +    "phpdocumentor/reflection-docblock": "^5.3",
@Moemen-Gaballah 
They are already removed, rebase your branch.

2022-12-03 11:39 UTC, imdhemy requested changes

2022-12-03 11:39 UTC, imdhemy commented on notes
> +docker exec -it siklid_php php bin/console lexik:jwt:generate-keypair
We can mention the command that generates the keypair in the [dev env guide](https://github.com/piscibus/siklid-api/blob/1.x/docs/contributing/development.md#commands), and remove this file.

2022-12-03 12:29 UTC, Moemen-Gaballah commented on composer.json
> +    "phpdocumentor/reflection-docblock": "^5.3",
Done remove It.

2022-12-03 18:07 UTC, imdhemy commented on siklid.api.v1.postman_collection.json
> +{
@Moemen-Gaballah CC

2022-12-03 18:10 UTC, imdhemy commented
@Moemen-Gaballah 
Could you please remove the postman collection as well?

--

Regarding Redis, I'm still unsure if we will use Predis or PHPredis extension without Predis. I'm investigating this and I will keep you posted.

2022-12-03 18:12 UTC, imdhemy commented on src/Controller/Auth/LogoutInterface.php
> +class LogoutInterface extends ApiController implements TokenAuthenticatedInterface
Why does this class have `Interface` in its name?

2022-12-03 18:21 UTC, imdhemy commented on src/Controller/Auth/LogoutInterface.php
> +        $cacheItem = $cache->getItem('users.invalidToken');
@Moemen-Gaballah 

As you already know Redis is an In-Memory DB, so storing all the black listed tokens of all users in a single cache entry is not a good idea. Besides, this approach does not provide any mean of invalidating the cached values.

In addition, you are blacklisting the access token, but the user still have the refresh token, we need to black list it as well.

2022-12-03 18:29 UTC, imdhemy commented on config/packages/cache.yaml
> +            #my.dedicated.cache: null
You can find more information on [SOF](https://stackoverflow.com/questions/2287967/why-is-it-recommended-to-have-empty-line-in-the-end-of-a-source-file).

2022-12-03 18:32 UTC, imdhemy commented on src/Controller/TokenAuthenticatedInterface.php
> +<?php
So, what about just checking the `Authorization` header? All auth-protected routes require it.

2022-12-08 12:06 UTC, closed without merging