User logout
piscibus/siklid-api pull request #161
Opened 2022-12-12 13:18 UTC by Moemen-Gaballah

| Q             | A                                                                  |
|---------------|--------------------------------------------------------------------|
| Branch?       | 1.x                                              |
| Bug fix?      | no                                                             |
| New feature?  | yes                   |
| Deprecations? |no  |
| Tickets       | Fix #54              |
| License       | MIT                                                                |

2022-12-12 14:42 UTC, imdhemy commented
Unfortunately, this PR breaks Testsuite. It breaks all tests when a user is not logged in. Please, Fix all issues and request a review again. Thanks!

2022-12-15 09:55 UTC, imdhemy requested changes
This is good progress. I added some comments, could you please take a look? Thanks!

2022-12-15 09:55 UTC, imdhemy commented on src/Controller/Auth/LogoutController.php
> +        $userId = (string)$this->getUser()->getId();
It would be better to assert that the user is an instance of the `User` class before accessing the `getId()` method.

2022-12-15 09:55 UTC, imdhemy commented on src/EventSubscriber/TokenSubscriber.php
> +            $userId = (string)$this->tokenStorage->getToken()->getUser()->getId();
And here, asserting that the user is an instance of the `User` class is necessary.

2022-12-15 11:24 UTC, imdhemy commented on src/Controller/Auth/LogoutController.php
> +        $userId = (string)$this->getUser()->getId();
@Moemen-Gaballah 
This is not enough. Use a variable for the user.

```php
$user = $this->getUser();
assert($user instanceof User);
```

2022-12-18 09:26 UTC, Moemen-Gaballah commented
refactor code from controller to another layer (actions).

2022-12-24 13:43 UTC, imdhemy commented
@Moemen-Gaballah I updated this branch with the latest changes on `1.x`, so don't forget to pull changes before updating the code locally.

2022-12-24 13:46 UTC, imdhemy requested changes
- A single entry point for logout is required.
- I'm not sure if we need to add new services to handle revoking the tokens or extend current token managers with new methods. [Investigation is required]
-IMHO, the chosen names could be better

2022-12-26 13:25 UTC, Moemen-Gaballah commented
Refactor Logout (A single entry point for logout is required)

2023-01-23 16:54 UTC, imdhemy approved these changes
This PR could be improved by adding an adapter for the token packages to improve the token manager, but this is in the scope of another PR. We can merge this PR as is and then add the adapter in another PR.

2023-01-24 09:59 UTC, merged