[1.x] View Flashcard
piscibus/siklid-api pull request #173
Opened 2022-12-23 12:06 UTC by mgamal92

| Q             | A                                                                  |
|---------------|--------------------------------------------------------------------|
| Branch?       | 1.x                                              |
| Bug fix?      |no                                                             |
| New feature?  | yes                   |
| Deprecations? | no  |
| Tickets       | Fix #137 ...            |
| License       | MIT                                                                |

2023-01-10 10:40 UTC, imdhemy requested changes
Thanks a lot for investing time in this PR. I added some comments. Feel free to discuss about the.

2023-01-10 10:40 UTC, imdhemy commented on src/Controller/FlashcardController.php
> +        return $this->ok($action->setFlashcard($flashcard)->execute(), ['box:show', 'resource:read']);
The `Box` document has no `box:show` serialization group. It should be `box:read` instead.

2023-01-10 10:40 UTC, imdhemy commented on tests/Feature/Flashcard/CreateFlashcardTest.php
> +    use FlashcardFactoryTrait;
This trait is not used anywhere in this class.

2023-01-10 10:40 UTC, imdhemy commented on tests/Feature/Flashcard/ViewFlashcardTest.php
> +    public function user_can_show_single_flashcard(): void
This test does not run. A `@test` comment is required.

2023-01-10 10:40 UTC, imdhemy commented on tests/Feature/Flashcard/ViewFlashcardTest.php
> +        $this->assertExists(Flashcard::class, ['id' => $flashcard->getId()]);
Assertion of existence has nothing to add here. We need to assert the returned response contains the requested flashcard.

2023-01-10 10:40 UTC, imdhemy commented on src/Controller/FlashcardController.php
> +    public function show(ViewFlashcard $action, Flashcard $flashcard): JsonResponse
Parameter conversion looks cleaner somehow. But, I'm still not sure, if should we expose Documents to the Controllers or just expose actions as a single entry point to the business logic.

2023-01-10 13:53 UTC, mgamal92 commented on tests/Feature/Flashcard/CreateFlashcardTest.php
> +    use FlashcardFactoryTrait;
Done

2023-01-10 13:53 UTC, mgamal92 commented on tests/Feature/Flashcard/ViewFlashcardTest.php
> +    public function user_can_show_single_flashcard(): void
Done

2023-01-10 13:53 UTC, mgamal92 commented on src/Controller/FlashcardController.php
> +    public function show(ViewFlashcard $action, Flashcard $flashcard): JsonResponse
I didn't get that point

2023-01-10 13:54 UTC, mgamal92 commented on src/Controller/FlashcardController.php
> +        return $this->ok($action->setFlashcard($flashcard)->execute(), ['box:show', 'resource:read']);
Done

2023-01-11 09:22 UTC, imdhemy commented on src/Controller/FlashcardController.php
> +    public function show(ViewFlashcard $action, Flashcard $flashcard): JsonResponse
This is a tradeoff anyway. The current approach is fine. Let's discuss this after fixing the feature test.

2023-04-02 17:05 UTC, mgamal92 commented
@imdhemy check it

2023-04-02 17:31 UTC, imdhemy approved these changes
@mgamal92 Thank you!

2023-04-02 17:32 UTC, merged